image: 'rust:latest'

stages:
  - test
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y llvm-dev libclang-dev clang libsqlite3-dev

test:
  stage: test
  script:
    - rustc --version
    - cargo --version

build:
  stage: bulid
  script:
    - cargo build --release

cache:
  paths:
    - apt/
    - cargo/
    - target/
