[package]
name = "increstore"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.3"
#async-std = "1.5"
async-std = { path = "../async-std" }
bytesize = "1.0.0"
env_logger = "0.7.1"
futures = { version = "0.3.4", features = ["thread-pool"] }
highway = "0.3.0"
log = "0.4.8"
pbr = "1.0.2"
rayon = "1.3.0"
rusqlite = "0.21.0"
sha1 = "0.6.0"
stopwatch = "0.0.7"
tar = "0.4.26"
tempfile = "3.1.0"
thiserror = "1.0.11"
time = "0.1"
#xdelta3 = { git = "https://github.com/yjh0502/xdelta3-rs" }
xdelta3 = { path = "../xdelta3-rs" }
zip = "0.5.4"
hyper = "0.13.3"
hyper-tls = "0.4.1"
tokio = { version = "0.2.13", features = ["fs"] }
walkdir = "2.3.1"

[profile.release]
debug = true
