[package]
name = "increstore"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5"
rusqlite = "0.21.0"
sha1 = "0.6.0"
tar = "0.4.26"
time = "0.1"
xdelta3 = { path = "../xdelta3-rs" }
zip = "0.5.4"
env_logger = "0.7.1"
log = "0.4.8"
argh = "0.1.3"
stopwatch = "0.0.7"
pbr = "1.0.2"
highway = "0.3.0"
tempfile = "3.1.0"
futures = "0.3.4"

[profile.release]
debug = true
