[package]
name = "increstore"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
bytesize = "1"
env_logger = "0.9"
futures = { version = "0.3.4", features = ["thread-pool"] }
highway = "0.6"
log = "0.4"
pbr = "1"
rayon = "1.3"
rusqlite = { version = "0.26", features = ["time"] }
sha1 = "0.6"
stopwatch = "0.0.7"
tar = "0.4"
tempfile = "3"
time = "0.3"
xdelta3 = { git = "https://github.com/yjh0502/xdelta3-rs" }
zip = "0.5"
walkdir = "2"
memmap = "0.7"
flate2 = "1"
failure = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["compat"] }

[profile.release]
debug = true
